services:

  app-suportes-frontend:
    image: ${DOCKER_USERNAME:-suportess}/app-suportes-frontend:${IMAGE_TAG:-latest}
    container_name: app-suportes-frontend
    restart: unless-stopped
    env_file: .env.app
    expose:
      - "3000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-suportes-frontend.rule=Host(`suportes.tec.br`)"
      - "traefik.http.routers.app-suportes-frontend.entrypoints=websecure"
      - "traefik.http.routers.app-suportes-frontend.tls=true"
      - "traefik.http.routers.app-suportes-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-suportes-frontend.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
    name: proxy
